name: Deploy Code Reviewer to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: |
          npm run build
          npm run package
          cd dist && zip -r index.js.zip index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name irin-code-reviewer-bot \
            --zip-file fileb://$(pwd)/dist/index.js.zip \
            --publish

      - name: Wait for function update to complete
        run: |
          echo "Waiting for Lambda function update to complete..."
          sleep 30
          aws lambda wait function-active-v2 --function-name irin-code-reviewer-bot

      - name: Update function configuration
        run: |
          aws lambda update-function-configuration \
            --function-name irin-code-reviewer-bot \
            --environment "{\"Variables\":{\
              \"GITHUB_TOKEN\":\"${{ secrets.GH_TOKEN }}\"\
            }}"